### ISSUE TITLE
How to run models?

### ISSUE THREAD

**Issue by chiyuzhang94** [Jyonn/Legommenders#2]
Hi @Jyonn ,

I would like to ask how to run the models (such as NRMS) with your tool? Any guidance? 

Best,
Chiyu

**Comment by Jyonn** [comment]
Hi Chiyu, you can try the following command.

```bash
python worker.py
 --data config/data/<dataset>.yaml 
 --embed config/embed/null.yaml 
 --model config/model/lego_nrms.yaml 
 --exp config/exp/tt-naml.yaml  
 --embed_hidden_size 64 
 --hidden_size 64 
 --lr 0.001 
 --batch_size 256
```

**Comment by chiyuzhang94** [comment]
Thanks.

I wonder what format the dataset should be look like. Does the code support multi-gpu training?

**Comment by Jyonn** [comment]
You can download the dataset from [here](https://github.com/Jyonn/ONCE/releases).
Currently, we only support single GPU running.

**Comment by chiyuzhang94** [comment]
> You can download the dataset from [here](https://github.com/Jyonn/ONCE/releases). Currently, we only support single GPU running.

Hi @Jyonn 

I got a question about how to covert to my tsv files into your data format for training because I have different datasets. 
I know we had some discussions about the data preprocessing but I wonder what the scripts used to generate the final dataset for training model.

**Comment by Jyonn** [comment]
Hi Chiyu,

You can refer to [here](https://github.com/Jyonn/Legommenders/blob/master/process/mind/processor_unitokv3.py), which is a data preprocessing pipeline for converting the MIND data (csv file) to our format. 

Basically, you should prepare several dataframes, such as item df, user history df, and interaction (train/dev/test) df. For each df, you are required to prepare a `unitok` to tokenize this part of data.

**Comment by chiyuzhang94** [comment]
> You can download the dataset from [here](https://github.com/Jyonn/ONCE/releases). Currently, we only support single GPU running.

Hi @Jyonn ,

I am trying run the code with your orginal dataset from the Google drive. 
Here is my command. However, it failed to find `'data/MIND-small/neg/meta.data.json'`. I cannot see this neg folder in your data. Can you take a look at this issue?

```
python worker.py \
 --version small \
 --data config/data/mind.yaml \
 --embed config/embed/null.yaml \
 --model config/model/lego_nrms.yaml \
 --exp config/exp/tt-naml.yaml \
 --embed_hidden_size 64 \
 --hidden_size 64 \
 --lr 0.001 \
 --batch_size 256
```
Error:
```
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/UniTok/meta.py", line 77, in __init__
    data = self.load()
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/UniTok/meta.py", line 110, in load
    return json.load(open(self.path))
FileNotFoundError: [Errno 2] No such file or directory: 'data/MIND-small/neg/meta.data.json'
```

I found your yaml file specified this:
```
 union:
    - ${data.base_dir}/user-grp
    - ${data.base_dir}/neg
 ```
But these are not in your provided dataset.

**Comment by Jyonn** [comment]
Hi Chiyu,

I guess I have combined the user-grp and neg data into the unified user folder. Please rewrite this snippet into:

``` 
union:
    - ${data.base_dir}/user
```

Sorry for the inconvenience.

**Comment by chiyuzhang94** [comment]
Thanks. I passed this issue but got a new error:

```
Traceback (most recent call last):
  File "/data/home/chiyu/Legommenders/worker.py", line 484, in <module>
    worker = Worker(config=configuration)
  File "/data/home/chiyu/Legommenders/worker.py", line 58, in __init__
    self.controller = Controller(
  File "/data/home/chiyu/Legommenders/loader/controller.py", line 91, in __init__
    self.embedding_hub.register_depot(self.item_hub)
  File "/data/home/chiyu/Legommenders/loader/embedding/embedding_hub.py", line 127, in register_depot
    vocab_name = depot.get_vocab(col)
  File "/data/home/chiyu/miniconda3/envs/py310/lib/python3.10/site-packages/UniTok/unidep.py", line 499, in get_vocab
    return self.cols[col_name].voc.name
KeyError: 'title'
```

**Comment by Jyonn** [comment]
Hi Chiyu,

The published dataset contains news attributes tokenized by diverse tokenizers. You can use `unitok <path>` command to have a look at all the columns provided by the published data if your `unitok` version is `3.5.1` or above.

```
        UniDep (2.0): .

        Sample Size: 65238
        Id Column: nid
        Columns:
                nid, vocab nid (size 65238)
                title-bert, vocab bert (size 30522), max length 20
                abs-bert, vocab bert (size 30522), max length 50
                summarizer-bert, vocab bert (size 30522), max length 25
                cat-token, vocab cat (size 18)
                subcat-token, vocab subcat (size 270)
                cat-bert, vocab bert (size 30522), max length 4
                subcat-bert, vocab bert (size 30522), max length 8
                cat-llama, vocab llama (size 32000), max length 4
                subcat-llama, vocab llama (size 32000), max length 10
                title-llama, vocab llama (size 32000), max length 20
                abs-llama, vocab llama (size 32000), max length 50
                summarizer-llama, vocab llama (size 32000), max length 25
```

In this case, you need to modify the data configuration like:
```
item:
  filter_cache: true
  depot: ${data.base_dir}/news
  order:
    - title-bert
    - cat-token
  append:
    - nid
  lm_col: title-bert  # add this line
```

**Comment by chiyuzhang94** [comment]
Thanks. This can solved the issue. 

I also got error of "fake_col: fake" and solved it by removing this line in the yaml file. 
I just wonder what this `fake_col` is for and if it is safe to remove it.

**Comment by Jyonn** [comment]
It is for other project. Yon can remove it.

**Comment by chiyuzhang94** [comment]
> Hi Chiyu, you can try the following command.
> 
> ```shell
> python worker.py
>  --data config/data/<dataset>.yaml 
>  --embed config/embed/null.yaml 
>  --model config/model/lego_nrms.yaml 
>  --exp config/exp/tt-naml.yaml  
>  --embed_hidden_size 64 
>  --hidden_size 64 
>  --lr 0.001 
>  --batch_size 256
> ```

Hi @Jyonn ,
I have question about running job with and without pretrained LMs. For example, how to make the configures for NRMS or NRMS-PLM?

**Comment by Jyonn** [comment]
Here are model configurations for NRMS and NRMS-BERT:

NRMS:
```
name: NRMS
meta:
  item: Attention
  user: Attention
  predictor: Dot
config:
  use_neg_sampling: true
  use_item_content: true
  hidden_size: ${hidden_size}$
  embed_hidden_size: ${embed_hidden_size}$
  neg_count: 4
  item_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: true
```


NRMS-Bert:
```
name: NRMS-Bert
meta:
  item: Bert
  user: Attention
  predictor: Dot
config:
  use_news_content: true
  max_news_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: ${embed_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  news_config:
    llm_dir: bert-base-uncased
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
```

You can also add `--item_lr 0.0001` in the command that indicates a slower learning rate of the PLMs, set a smaller `batch_size` if occuring OOM, and add `--embed_hidden_size 768`.

For now, we inherently (configuration-only) support LLaMA and Bert series. For other PLMs, you can refer to `model/operators/bert_operator.py` and design new operators.

**Comment by chiyuzhang94** [comment]
Hi @Jyonn ,

I have a question about saving model predictions. Now, I have done the model training. I wonder how to load the checkpoint, run on test set, and save the model predictions. Also, at the end of training, you evaluate on the test set, can we save both predictions and gold labels to a file?

**Comment by Jyonn** [comment]
Hi Chiyu,

To test the model only, please use `--exp exp/test.yaml`. It will automatically load the best model.

To save the predictions, you can write a new method based on the `evaluate` method on the `Worker` class. Save `score_series` to the file in your new method, and call it in the `test` method.

Thanks for your advise. This feature would probably be involved in our next major update.

**Comment by chiyuzhang94** [comment]
Hi @Jyonn

I wonder how to run fastformer. I cannot find any specific experiment configure for fastformer in `exp`. Which exp configure should I use?

I also wonder what these "plmnr-*" models in `model/llm/`. I do not see they use any PLM in the configure file. Any comments?

**Comment by Jyonn** [comment]
Fastformer: `--model config/model/lego_fastformer.yaml`. You can use `--exp tt-naml.yaml`.

`PLMNR-*` are early version configurations. You can still use them, but they only train transformer network from scratch with specific number of layers. If you want to load pretrained model, please use `BERT-*` series.

**Comment by chiyuzhang94** [comment]
Got it. Thanks. 

For BERT-* series, I wonder how I should modify your yaml file to finetune the whole PLM without using LoRA. Could you give any guidance?

**Comment by Jyonn** [comment]
You can use `--lora 0 --layer 0`.

**Comment by chiyuzhang94** [comment]
> --layer 0

Hi @Jyonn ,

I tried to run BERT-NRMS, but encountered some argument errors. I modified the yaml file as follows. However, even with the batch size set to 1, I still encountered a GPU Out Of Memory (OOM) error. Any suggestions? 

```
name: BERT-NRMS.D${model.config.hidden_size}.L${model.config.news_config.layer_split}.Lora${model.config.news_config.lora}
meta:
  item: Bert
  user: Attention
  predictor: Dot
config:
  use_news_content: true
  use_neg_sampling: true
  use_item_content: true
  use_fast_eval: ${fast_eval}$
  max_news_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: ${embed_hidden_size}$
  hidden_size: ${hidden_size}$
  neg_count: 4
  news_config:
    llm_dir: bert-base-uncased
    layer_split: ${layer}$
    lora: ${lora}$
    lora_r: ${lora_r}$
  item_config:
    llm_dir: bert-base-uncased
    layer_split: ${layer}$
    lora: ${lora}$
    lora_r: ${lora_r}$
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
```

**Comment by Jyonn** [comment]
Hi Chiyu,

Which GPU device do you use? You may add `max_item_content_batch_size: 64  # or 512` to the model config. But it is not possible even if the batch size is set to 1. Could you provide the entire config dict which is printed at the very beginning in [00:00:00].

**Comment by Jyonn** [comment]
BTW, you should extract BERT word embedding to a numpy file, and use `--embed config/embed/bert-token.yaml`.

```
name: bert-token
embeddings:
  -
    vocab_name: bert
    vocab_type: numpy
    path: <path-to-embedding>
    frozen: ${frozen}$
```
